# Generated by Django 5.2.1 on 2025-05-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_username_alter_otp_otp_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
